### PR TITLE
Added klov support (#67)

### PR DESCRIPTION
**Pull request by msingh3**
Added klov support to the project. Klov and mongoDb can be customized using ExtentProperties

### CODE REVIEW

**Comment by buekera** [comment]
Looks good to me!

@email2vimalraj can you please confirm and merge?

**Comment by email2vimalraj** [comment]
@msingh3 : Thanks for your PR. Appreciate your efforts. Looks good to me. Give me a day, I'll run in my machine tonight with klov server support and then merge once I've seen the report.

**Comment by buekera** [comment]
Some progress on this?

**Comment by baraths84** [comment]
Is this on hold.. pls advise

**Comment by email2vimalraj** [comment]
@msingh3 : I'm extremely sorry for delaying this PR due to some personal reasons. I had look at the code and looks good. Could you please update the README with instructions on how to use this to enable the klov reporting? We are good to merge this then.

**Comment by msingh3** [comment]
Updated Readme file with instructions on how to enable Klov reporting.

**Pull request merged**
